export const COLOR_ACTIONS = {
  INCREMENT: {
    RED: "INCREMENT_RED",
    GREEN: "INCREMENT_GREEN",
    BLUE: "INCREMENT_BLUE",
  },
  DECREMENT: {
    RED: "DECREMENT_RED",
    GREEN: "DECREMENT_GREEN",
    BLUE: "DECREMENT_BLUE",
  },
};